accounts/urls.py
from django.urls import path,re_path, include
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'login/$',
    auth_views.LoginView.as_view(template_name = 'accounts/login.html'),
    name = 'login'),
    re_path(r'logout/$',auth_views.LogoutView.as_view(), name = 'logout'),
    re_path(r'signup/$', views.SignUp.as_view(), name = 'signup')
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,re_path, include
from simplesocial import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.HomePage.as_view(), name = 'home'),
    re_path(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^test/$', views.TestPage.as_view(), name = 'test'),
    re_path(r'^thanks/$', views.ThanksPage.as_view(), name = 'thanks')
]

accounts/models.py
from django.db import models
from django.contrib import auth


# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return f"@{self.username}"

communities/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
import misaka 

posts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

    class Meta():
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import (FormView, CreateView,
                                        UpdateView, DeleteView)

from accounts import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

communities/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render

# Create your views here.

simplesocial/views.py
from django.views.generic import TemplateView


class TestPage(TemplateView):

    template_name = 'test.html'


class ThanksPage(TemplateView):

    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}

<div class="container">
    <h1>Log In!</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class = 'btn btn-default' name="" value="Login">

    </form>

</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}

<div class="container">
    <h1>Sign Up!</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class = 'btn btn-default' name="" value="Sign Up">

    </form>

</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Montserrat Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

  </head>
  <body>

    <nav class = 'navbar mynav' role='navigation' id = 'navbar'>
      <div class="container">
        <a class = 'navbar-brand mynav' href="{% url 'home' %}">Star Social</a>

        <ul class = 'nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a href="#">Post</a></li>
            <li><a href="#">Groups</a></li>
            <li><a href="#">Create Group</a></li>
            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>

          {% else %}
            <li><a href="#">Groups</a></li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>

          {% endif %}

        </ul>
      </div>

    </nav>

    <div class="container mycontent">

      {% block content %}
      {% endblock %}

    </div>



  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h1>Welcome to Star Social!</h1>

{% endblock %}

templates/test.html
{% extends 'base.html'%}

{% block content %}

  <h1>You're now logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html'%}

{% block content %}

  <h1>Tnanks for visiting! Come back soon!!</h1>


{% endblock %}